## Indexing: Advanced Patterns

In [1]:
import numpy as np

In [9]:
# Exercise 2.1

a = np.arange(1, 17).reshape(4, 4)

print(a[1, :]) # [5, 6, 7, 8]
print(a[:, 2]) # [3, 7, 11, 15]
print(a[1:3, 1:3]) # [[6, 7], [10, 11]]
print(a[::2, ::2]) # [[1, 3], [9, 11]]
print(a[-1, :]) # [13, 14, 15, 16]
print(a[:, -2:]) # [[3, 4], [7, 8], [11, 12], [15, 16]]
print(a[0:3:2, 1:4:2]) # [[2, 4], [10, 12]]

[5 6 7 8]
[ 3  7 11 15]
[[ 6  7]
 [10 11]]
[[ 1  3]
 [ 9 11]]
[13 14 15 16]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
[[ 2  4]
 [10 12]]


In [ ]:
# Exercise 2.2

np.random.seed(0)
X = np.random.randn(100, 5)


In [58]:
# a)
print(X[X[:, 0] > 0]) # 2D array
# b)
print(X[np.abs(X[:, 2]) > 1.5]) # 2D array
# c)
print(np.all(X > 0, 1).sum()) # scalar
# d)
X[X > 2.0] = 2.0
assert X.max() == 2.0
# e)
mask = (X > -0.5) & (X < 0.5) # shape (100, 5)
# f)
mask.sum(0) # 1D array

[[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799]
 [ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826  0.3130677  -0.85409574]
 [ 0.15494743  0.37816252 -0.88778575 -1.98079647 -0.34791215]
 [ 0.15634897  1.23029068  1.20237985 -0.38732682 -0.30230275]
 [ 0.42833187  0.06651722  0.3024719  -0.63432209 -0.36274117]
 [ 0.72909056  0.12898291  1.13940068 -1.23482582  0.40234164]
 [ 1.89588918  1.17877957 -0.17992484 -1.07075262  1.05445173]
 [ 0.70657317  0.01050002  1.78587049  0.12691209  0.40198936]
 [ 1.8831507  -1.34775906 -1.270485    0.96939671 -1.17312341]
 [ 1.94362119 -0.41361898 -0.74745481  1.92294203  1.48051479]
 [ 1.86755896  0.90604466 -0.86122569  1.91006495 -0.26800337]
 [ 0.8024564   0.94725197 -0.15501009  0.61407937  0.92220667]
 [ 0.37642553 -1.09940079  0.29823817  1.3263859  -0.69456786]
 [ 0.67643329  0.57659082 -0.20829876  0.39600671 -1.09306151]
 [ 0.94447949 -0.91282223  1.11701629 -1.31590741 -0.46

array([36, 36, 37, 38, 48])

In [93]:
# Exercise 2.3

np.random.seed(7)
data = np.random.randn(50, 4)
labels = np.random.randint(0, 3, size=50)

In [131]:
# a)
print(data[[0, 7, 13, 42]]) # (4, 4)
# b)
mask = labels == 1
print(data[mask])
print(mask.sum())
# c)
print(data[np.random.choice(50, size=10, replace=False)].shape)
print(data[np.random.permutation(50)[:10]].shape)
# d)
print(data[(labels == 0) | (labels == 2)])
# e)
print(data[np.argsort(data[:, 3])])

[[ 1.6905257  -0.46593737  0.03282016  0.40751628]
 [ 1.04939655 -0.41647432 -0.74255353  1.07247013]
 [ 0.10143399  0.25257774 -0.1323772  -0.30947634]
 [-1.07089251 -0.81220858 -0.81708025  0.1923077 ]]
[[ 0.55458031  0.12388091  0.27445992 -1.52652453]
 [-1.65107559  0.53542936 -2.0644148  -0.66215934]
 [ 0.84073324 -0.1799864   0.56806189 -0.7528372 ]
 [ 0.26941163 -0.52460462  1.91201886  0.23730185]
 [-1.43496347  0.50162412 -0.09477545  1.19308592]
 [-0.36881847 -1.90636988 -0.09961063  1.6995373 ]
 [-0.38342312 -0.88985686 -1.19359192 -1.05001681]
 [-0.01224219 -0.07566346 -0.67364519 -0.05586745]
 [ 2.25994699  0.86903933 -0.34211702 -0.47192665]
 [ 0.96420048  0.28363642 -0.61692195 -0.36228223]
 [-0.52097234  0.20972206 -1.07798489 -1.83242597]
 [-0.7110532   0.49612542 -0.53085375 -1.12196239]
 [-0.19385632  0.69729411  1.0919388   1.71438025]
 [ 0.4763377   1.11229049 -0.69659102  0.5829703 ]]
14
(10, 4)
(10, 4)
[[ 1.69052570e+00 -4.65937371e-01  3.28201637e-02  4.07516283

In [133]:
# Exercise 2.4

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
b = a[0:2, 0:2]
b[0, 0] = 999
print(a[0, 0]) # changed
c = a[a > 5]
c[1] = 999
print(a) # not changed
d = a[[0, 1], :]
d[1, 1] = 777
print(a) # not changed
e = a[0:2, 0:2].copy()
e[0, 0] = 555
print(a[0, 0]) # not changed
f = a.reshape(9)
f[0] = 111
print(a[0, 0]) # changed
g = a.T
g[0, 0] = 222
print(a[0, 0]) # changed
# Rule: slicing, reshape, and transpose return views (share memory with the original).
# Boolean indexing, fancy indexing, and .copy() always return copies (independent memory).

999.0
[[999.   2.   3.]
 [  4.   5.   6.]
 [  7.   8.   9.]]
[[999.   2.   3.]
 [  4.   5.   6.]
 [  7.   8.   9.]]
999.0
111.0
222.0
