## Broadcasting: Deep Drills

In [75]:
import numpy as np

In [76]:
# Exercise 3.1

# (3,)       + (3,)        → Valid (3,)
# (1, 3)     + (3, 1)      → Valid (3, 3)
# (4, 3)     + (3,)        → Valid (4, 3)
# (4, 3)     + (4, 1)      → Valid (4, 3)
# (4, 3)     + (1,)        → Valid (4, 3)
# (2, 4, 3)  + (4, 3)      → Valid (2, 4, 3)
# (2, 4, 3)  + (3,)        → Valid (2, 4, 3)
# (2, 4, 3)  + (4, 1)      → Valid (2, 4, 3)
# (2, 4, 3)  + (2, 1, 3)   → Valid (2, 4, 3)
# (3, 1)     + (1, 4)      → Valid (3, 4)
# (5, 3)     + (3, 5)      → Error (3rd rule)
# (1, 1, 4)  + (3, 1, 1)   → Valid (3, 1, 4)

In [77]:
a = np.array([1, 2, 3])
print((a + a).shape) # (3,) + (3,) = (3,)
b = np.arange(3).reshape(1, 3)
c = b.reshape(3, 1)
print((b + c).shape) # (1, 3) + (3, 1) = (3, 3)
d = np.arange(12).reshape(4, 3)
print((d + a).shape) # (4, 3) + (3,) = (4, 3)
e = np.arange(4).reshape(4, 1)
print((d + e).shape) # (4, 3) + (4, 1) = (4, 3)
f = np.array([1])
print((d + f).shape) # (4, 3) + (1,) = (4, 3)
g = np.arange(24).reshape(2, 4, 3)
print((g + d).shape) # (2, 4, 3) + (4, 3) = (2, 4, 3)
print((g + a).shape) # (2, 4, 3) + (3,) = (2, 4, 3)
print((g + e).shape) # (2, 4, 3) + (4, 1) = (2, 4, 3)
h = np.arange(6).reshape(2, 1, 3)
print((g + h).shape) # (2, 4, 3) + (2, 1, 3) = (2, 4, 3)
i = np.arange(4).reshape(1, 4)
print((c + i).shape) # (3, 1) + (1, 4) = (3, 4)
j = np.arange(15).reshape(5, 3)
k = j.reshape(3, 5)
# print((j + k).shape) <- Error, can't broadcast (5, 3) and (3, 5)
l = np.arange(4).reshape(1, 1, 4)
m = np.arange(3).reshape(3, 1, 1)
print((l + m).shape) # (1, 1, 4) + (3, 1, 1) = (3, 1, 4)

(3,)
(3, 3)
(4, 3)
(4, 3)
(4, 3)
(2, 4, 3)
(2, 4, 3)
(2, 4, 3)
(2, 4, 3)
(3, 4)
(3, 1, 4)


In [78]:
# Exercise 3.2
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30])

# a)
a = a.reshape(4, 1)
print(a + b)
print((a + b).shape)
print((a + b)[0])
print((a + b)[:, 0])

# b)
print(a * b)
print((a * b).shape)
print(a / (a + b))
print((a / (a + b)).shape)


[[11 21 31]
 [12 22 32]
 [13 23 33]
 [14 24 34]]
(4, 3)
[11 21 31]
[11 12 13 14]
[[ 10  20  30]
 [ 20  40  60]
 [ 30  60  90]
 [ 40  80 120]]
(4, 3)
[[0.09090909 0.04761905 0.03225806]
 [0.16666667 0.09090909 0.0625    ]
 [0.23076923 0.13043478 0.09090909]
 [0.28571429 0.16666667 0.11764706]]
(4, 3)


In [79]:
# Exercise 3.3

np.random.seed(1)
A = np.random.randn(5, 3)
B = np.random.randn(8, 3)
A = A.reshape(5, 1, 3)
B = B.reshape(1, 8, 3)
points_diff = A - B
points_squared = np.square(points_diff)
points_sum = np.sum(points_squared, axis=2)
D = np.sqrt(points_sum)

A_vs_A = np.sqrt(np.sum(np.square(A.reshape(5,1,3) - A.reshape(1,5,3)), axis=2))
print(np.diag(A_vs_A))

[0. 0. 0. 0. 0.]


In [85]:
# Exercise 3.4
np.random.seed(42)
X = np.random.randn(1000, 8) * np.array([1, 5, 0.1, 100, 2, 50, 0.5, 10])
X_mean = np.mean(X, axis=0)
print(X_mean.shape)
X_std = np.std(X, axis=0)
print(X_std.shape)
X_norm = (X - X_mean) / X_std
print(X_norm.shape)
assert np.all(np.isclose(X_norm.mean(axis=0), 0))
assert np.all(np.isclose(X_norm.std(axis=0), 1))

X_min = np.min(X, axis=0)
X_max = np.max(X, axis=0)
X_minmax = (X - X_min) / (X_max - X_min)
assert np.all((X_minmax >= 0) & (X_minmax <= 1))

(8,)
(8,)
(1000, 8)


In [100]:
# Exercise 3.5

np.random.seed(5)
batch = np.random.randn(32, 16)

W = np.random.randn(16, 8)
b = np.random.randn(8)
lin_transformation = batch @ W + b # shape (32, 8)
ReLU = np.maximum(0, lin_transformation)
print((ReLU == 0).sum() / ReLU.size)
W_batch = np.random.randn(32, 16, 8)
product = batch.reshape(32, 16, 1) * W_batch
print(product.sum(axis=1).shape)

0.4921875
(32, 8)
