## Numerical stability and common pitfalls

In [59]:
import numpy as np

In [60]:
# Exercise 7.1

print(np.isclose(0.1 + 0.2, 0.3))
print(np.float32(0.1) + np.float32(0.2) == np.float32(0.3))
print(np.isclose(np.sin(np.pi), 0.0))
print(np.sum(np.ones(10) * 0.1) == 1.0)

# Never use '==' to compare floating point numbers. This might result in errors due to floating-point
# errors. Instead use np.isclose() or np.allclose()


True
True
True
True


In [61]:
# Exercise 7.2

# a = np.array([200], dtype=np.int8) <- assigning this raises OverflowError, since int8 is [-128, 127]
a = np.array([100, 100, 100], dtype=np.int8)
print(a + a) # element-wise addition stil causes overflow without raising error (values fit individually)
print(a.astype(np.int32) + a.astype(np.int32))
print(a.sum())
print(a.sum().dtype) # int64 - numpy upcasted data type

c = np.array([20000, 20000], dtype=np.int16)
print(c + c) # element-wise overflow
print(c.astype(np.int32) + c.astype(np.int32))

[-56 -56 -56]
[200 200 200]
300
int64
[-25536 -25536]
[40000 40000]


In [ ]:
# Exercise 7.3

probs = np.array([0.5, 0.3, 0.2, 0.0])

# log_probs = np.log(probs) warns and returns -inf due to log(x) == -inf when x approaches 0

eps = 1e-9
log_probs_safe = np.log(probs + eps)
print(log_probs_safe)

counts = np.array([10, 5, 0, 3])
# ratios = probs / counts division by 0 error
np.where(counts == 0, 0.0, probs / np.where(counts == 0, 1, counts))

[ -0.69314718  -1.2039728   -1.60943791 -20.72326584]


array([0.05, 0.06, 0.  , 0.  ])

In [63]:
def log_sum_exp(x):
    """Numerically stable log(sum(exp(x))) for 1D array"""
    shifted = x - np.max(x)
    shifted_exp = np.exp(shifted)
    return np.log(shifted_exp.sum()) + np.max(x)

x = np.array([1000.0, 1001.0, 1002.0])
print(log_sum_exp(x))
# print(np.log(np.sum(np.exp(x)))) <- overflows

1002.4076059644444


In [64]:
# Exercise 7.4

a = np.array([1, 2, 3])
b = a.reshape(3, 1)
c = a.reshape(1, 3)

M = np.random.randn(3, 3)

print((M @ a).shape) # (3,)
print((M @ b).shape) # (3, 1)
print((a @ M).shape) # (3,)
print((b.T @ M).shape) # (1, 3)

print((a + a).shape) # (3,)
print((a + b).shape) # (3, 3)
print((a + c).shape) # (1, 3)
print((b + c).shape) # (3, 3)

# (n,) is flexible but dangerous when broadcasted with (1,n)/(n,1) - easily can go to (n,n) unintentionally

(3,)
(3, 1)
(3,)
(1, 3)
(3,)
(3, 3)
(1, 3)
(3, 3)
